import { StyleSheet } from 'react-native';
import { theme } from './colors';

export const constellationStyles = StyleSheet.create({
    container: {
        width: 355,
        height: 215,
        alignItems: 'center',
    },
    opDisplay: {
        position: 'absolute',
        top: -20,
        fontSize: 24,
        fontFamily: 'serif',
        fontWeight: 'bold',
    },
    anchor: {
        width: 0,
        height: 0,
        position: 'relative',
        top: 165, // Practice-area vertical center
    },
    operationLabelContainer: {
        position: 'absolute',
        top: -163.5, // Shifted up 1px to maintain a 9px logo-to-selector gap
        left: -176.5, // Centers the 353px width shape horizontally
        width: 353,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    operationLabel: {
        height: 36,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    operationTextLeft: {
        fontSize: 30,
        lineHeight: 36,
        fontFamily: 'Fredoka_400Regular',
    },
    operationTextRight: {
        fontSize: 30,
        lineHeight: 36,
        fontFamily: 'Fredoka_400Regular',
    },
    operationMiniIconLeft: {
        position: 'absolute',
        left: 7,
        top: (36 - 23) / 2,
        width: 23,
        height: 23,
        justifyContent: 'center',
        alignItems: 'center',
    },
    operationMiniIconRight: {
        position: 'absolute',
        right: 7,
        top: (36 - 23) / 2,
        width: 23,
        height: 23,
        justifyContent: 'center',
        alignItems: 'center',
    },
    card: {
        position: 'absolute',
        width: 160,
        height: 100,
        backgroundColor: theme.cardOperandBg,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        // Figma Shadow: X:0, Y:3, Blur:6, Color: #000 50%
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
        elevation: 6,
        zIndex: 2,
    },
    cardLeft: {
        top: -165,
        left: -187.5,
    },
    cardRight: {
        top: -165,
        left: 27.5,
    },
    cardResult: {
        position: 'absolute',
        top: -50,
        left: -97.5,
        width: 195,
        height: 100,
        backgroundColor: theme.cardResultBg,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
        elevation: 6,
        zIndex: 2,
    },
    cardAnswer: {
        position: 'absolute',
        top: 65,
        left: -97.5,
        width: 195,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2,
    },
    cardText: {
        fontSize: 90,
        fontWeight: '700',
        fontFamily: 'Nunito_700Bold',
        zIndex: 10,
    },
    ellipseLarge: {
        position: 'absolute',
        width: 270,
        height: 184,
        left: 0,
        top: -53,
        transform: [{ translateX: -135 }, { translateY: -92 }],
        zIndex: -1,
    },
    ellipseSmall: {
        position: 'absolute',
        width: 153,
        height: 130,
        left: 0,
        top: -26,
        transform: [{ translateX: -76.5 }, { translateY: -65 }],
        zIndex: -1,
    },
    circle: {
        position: 'absolute',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ translateX: -20 }, { translateY: -20 }],
        zIndex: 3,
    },
    circleMain: {
        left: 0,
        top: -85,
        backgroundColor: theme.operatorCircleBg,
    },
    circleInvLeft: {
        left: -123.5,
        top: -30,
        backgroundColor: theme.inverseCircleBg,
    },
    circleInvRight: {
        left: 123.5,
        top: -30,
        backgroundColor: theme.inverseCircleBg,
    }
});
